# change the followings to match your Github username and repo name
baseurl: "/tailpage" # the name of your github repo
url: "https://nmans01.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: Natavo
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Natavo
author-bio: Full-force Custom Order Management Software  # change to false to hide
author-image: logo.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: false
linkedin: false
medium: false
google-scholar: false
email: nate@centercityprint.com

# footer information
footer-msg: "Natavo"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: ""

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
