# change the followings to match your Github username and repo name
baseurl: "/tailpage" # the name of your github repo
url: "https://nmans01.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: N's Tailpage Test
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Nate Mansfield
author-bio: Fullstack dev  # change to false to hide
author-image: toro5.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/nmans01
facebook: false
instagram: false
github: https://github.com/nmans01
linkedin: false
medium: false
google-scholar: false
email: nate@centercityprint.com

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
